import 'dotenv/config';
import { PrismaClient } from '../src/app/generated/prisma/client.js';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});

const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🌱 Seeding CouponHunt database...');

  // Clean existing data
  await prisma.click.deleteMany();
  await prisma.couponCategory.deleteMany();
  await prisma.dealCategory.deleteMany();
  await prisma.storeCategory.deleteMany();
  await prisma.coupon.deleteMany();
  await prisma.deal.deleteMany();
  await prisma.category.deleteMany();
  await prisma.store.deleteMany();

  console.log('✅ Cleaned existing data');

  // === CATEGORIES ===
  const categories = await Promise.all([
    prisma.category.create({
      data: {
        name: 'Electronics',
        slug: 'electronics',
        description: 'Find the best deals on smartphones, laptops, gadgets, and electronic accessories.',
        image: '💻',
        metaTitle: 'Electronics Coupons & Deals',
        metaDescription: 'Save big on electronics with verified coupons and exclusive deals.',
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 1,
      },
    }),
    prisma.category.create({
      data: {
        name: 'Fashion',
        slug: 'fashion',
        description: 'Discover discounts on clothing, shoes, accessories, and more from top brands.',
        image: '👗',
        metaTitle: 'Fashion Coupons & Deals',
        metaDescription: 'Shop fashion for less with exclusive coupons and seasonal deals.',
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 2,
      },
    }),
    prisma.category.create({
      data: {
        name: 'Food & Dining',
        slug: 'food-dining',
        description: 'Save on food delivery, restaurant dining, and grocery shopping.',
        image: '🍕',
        metaTitle: 'Food & Dining Coupons & Deals',
        metaDescription: 'Delicious savings on food delivery and dining with verified coupons.',
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 3,
      },
    }),
    prisma.category.create({
      data: {
        name: 'Travel',
        slug: 'travel',
        description: 'Get the best prices on flights, hotels, and travel packages.',
        image: '✈️',
        metaTitle: 'Travel Coupons & Deals',
        metaDescription: 'Book your next trip for less with travel coupons and exclusive deals.',
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 4,
      },
    }),
    prisma.category.create({
      data: {
        name: 'Health & Beauty',
        slug: 'health-beauty',
        description: 'Discounts on skincare, makeup, supplements, and wellness products.',
        image: '💄',
        metaTitle: 'Health & Beauty Coupons & Deals',
        metaDescription: 'Look and feel great for less with health and beauty savings.',
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 5,
      },
    }),
    prisma.category.create({
      data: {
        name: 'Home & Living',
        slug: 'home-living',
        description: 'Save on furniture, home decor, appliances, and kitchen essentials.',
        image: '🏠',
        metaTitle: 'Home & Living Coupons & Deals',
        metaDescription: 'Transform your home for less with furniture and decor deals.',
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 6,
      },
    }),
    prisma.category.create({
      data: {
        name: 'Sports & Fitness',
        slug: 'sports-fitness',
        description: 'Deals on sportswear, gym equipment, fitness subscriptions, and more.',
        image: '🏋️',
        metaTitle: 'Sports & Fitness Coupons & Deals',
        metaDescription: 'Stay active for less with sports and fitness deals.',
        status: 'PUBLISHED',
        isFeatured: false,
        sortOrder: 7,
      },
    }),
    prisma.category.create({
      data: {
        name: 'Books & Education',
        slug: 'books-education',
        description: 'Discounts on books, courses, educational subscriptions, and learning tools.',
        image: '📚',
        metaTitle: 'Books & Education Coupons & Deals',
        metaDescription: 'Learn more for less with education and book deals.',
        status: 'PUBLISHED',
        isFeatured: false,
        sortOrder: 8,
      },
    }),
  ]);

  console.log(`✅ Created ${categories.length} categories`);

  // === STORES ===
  const stores = await Promise.all([
    prisma.store.create({
      data: {
        name: 'Amazon India',
        slug: 'amazon-india',
        logo: '🛒',
        shortDescription: 'India\'s largest online marketplace with millions of products.',
        description: 'Amazon.in is India\'s most popular online shopping destination, offering everything from electronics and fashion to groceries and home essentials. Find exclusive Amazon coupons, promo codes, and lightning deals.',
        websiteUrl: 'https://www.amazon.in',
        metaTitle: 'Amazon India Coupons & Deals - Up to 80% Off',
        metaDescription: 'Save on Amazon India with verified coupon codes, promo codes, and daily deals. Up to 80% off on electronics, fashion, and more.',
        status: 'PUBLISHED',
        isFeatured: true,
        isPopular: true,
        sortOrder: 1,
      },
    }),
    prisma.store.create({
      data: {
        name: 'Flipkart',
        slug: 'flipkart',
        logo: '🏪',
        shortDescription: 'India\'s leading e-commerce platform with great deals.',
        description: 'Flipkart is one of India\'s leading e-commerce platforms offering a wide range of products including electronics, fashion, home appliances, and more. Discover exclusive Flipkart offers and seasonal sales.',
        websiteUrl: 'https://www.flipkart.com',
        metaTitle: 'Flipkart Coupons & Offers - Best Deals Today',
        metaDescription: 'Get the best Flipkart deals with verified coupons and offer codes. Save on electronics, fashion, and daily essentials.',
        status: 'PUBLISHED',
        isFeatured: true,
        isPopular: true,
        sortOrder: 2,
      },
    }),
    prisma.store.create({
      data: {
        name: 'Myntra',
        slug: 'myntra',
        logo: '👠',
        shortDescription: 'India\'s premier fashion and lifestyle destination.',
        description: 'Myntra is India\'s leading fashion e-commerce platform, offering clothing, footwear, accessories, and home decor from 5000+ brands. Use Myntra coupons for extra savings on your fashion purchases.',
        websiteUrl: 'https://www.myntra.com',
        metaTitle: 'Myntra Coupons & Offers - Fashion Deals',
        metaDescription: 'Shop fashion for less with Myntra coupon codes and exclusive offers on clothing, shoes, and accessories.',
        status: 'PUBLISHED',
        isFeatured: true,
        isPopular: true,
        sortOrder: 3,
      },
    }),
    prisma.store.create({
      data: {
        name: 'Swiggy',
        slug: 'swiggy',
        logo: '🍔',
        shortDescription: 'Order food online from thousands of restaurants.',
        description: 'Swiggy is India\'s largest food delivery platform, delivering from thousands of restaurants. Save on every order with Swiggy coupons, promo codes, and exclusive offers for new and existing users.',
        websiteUrl: 'https://www.swiggy.com',
        metaTitle: 'Swiggy Coupons & Offers - Food Delivery Deals',
        metaDescription: 'Order food for less with Swiggy coupon codes and promo codes. Exclusive deals for new users.',
        status: 'PUBLISHED',
        isFeatured: true,
        isPopular: true,
        sortOrder: 4,
      },
    }),
    prisma.store.create({
      data: {
        name: 'Zomato',
        slug: 'zomato',
        logo: '🍽️',
        shortDescription: 'Food delivery and dining out offers.',
        description: 'Zomato delivers food from the best restaurants near you. Find exclusive Zomato promo codes, discount coupons, and cashback offers on food delivery and dining out.',
        websiteUrl: 'https://www.zomato.com',
        metaTitle: 'Zomato Coupons & Offers - Up to 60% Off',
        metaDescription: 'Save on Zomato food delivery with verified promo codes and coupons. Up to 60% off on your orders.',
        status: 'PUBLISHED',
        isFeatured: false,
        isPopular: true,
        sortOrder: 5,
      },
    }),
    prisma.store.create({
      data: {
        name: 'MakeMyTrip',
        slug: 'makemytrip',
        logo: '🌍',
        shortDescription: 'India\'s leading travel company for flights, hotels & holidays.',
        description: 'MakeMyTrip offers the best deals on flights, hotels, holiday packages, and bus tickets. Use MakeMyTrip coupons and promo codes to save on your next trip.',
        websiteUrl: 'https://www.makemytrip.com',
        metaTitle: 'MakeMyTrip Coupons & Offers - Travel Deals',
        metaDescription: 'Book flights and hotels for less with MakeMyTrip coupon codes and exclusive travel deals.',
        status: 'PUBLISHED',
        isFeatured: true,
        isPopular: true,
        sortOrder: 6,
      },
    }),
    prisma.store.create({
      data: {
        name: 'Nykaa',
        slug: 'nykaa',
        logo: '💅',
        shortDescription: 'India\'s top beauty and wellness destination.',
        description: 'Nykaa is India\'s premier beauty, wellness, and fashion destination, offering authentic products from 2500+ brands. Find Nykaa coupons and offers to save on skincare, makeup, and haircare.',
        websiteUrl: 'https://www.nykaa.com',
        metaTitle: 'Nykaa Coupons & Offers - Beauty Deals',
        metaDescription: 'Shop beauty products for less with Nykaa coupon codes and exclusive offers on skincare, makeup, and more.',
        status: 'PUBLISHED',
        isFeatured: true,
        isPopular: true,
        sortOrder: 7,
      },
    }),
    prisma.store.create({
      data: {
        name: 'Ajio',
        slug: 'ajio',
        logo: '🧥',
        shortDescription: 'Trendy fashion from Reliance\'s online fashion store.',
        description: 'AJIO is Reliance Retail\'s fashion and lifestyle platform offering curated brands, indie labels, and international fashion at great prices. Use AJIO coupons for additional savings.',
        websiteUrl: 'https://www.ajio.com',
        metaTitle: 'AJIO Coupons & Offers - Fashion Deals',
        metaDescription: 'Shop trendy fashion for less with AJIO coupon codes and exclusive offers.',
        status: 'PUBLISHED',
        isFeatured: false,
        isPopular: true,
        sortOrder: 8,
      },
    }),
    prisma.store.create({
      data: {
        name: 'Croma',
        slug: 'croma',
        logo: '📱',
        shortDescription: 'Tata\'s electronics retail chain with online deals.',
        description: 'Croma is India\'s leading electronics retail chain by Tata, offering the latest gadgets, appliances, and tech products. Find exclusive Croma deals and coupon codes for electronics.',
        websiteUrl: 'https://www.croma.com',
        metaTitle: 'Croma Coupons & Offers - Electronics Deals',
        metaDescription: 'Buy electronics for less with Croma coupon codes and exclusive deals on smartphones, laptops, and appliances.',
        status: 'PUBLISHED',
        isFeatured: false,
        isPopular: true,
        sortOrder: 9,
      },
    }),
    prisma.store.create({
      data: {
        name: 'Puma India',
        slug: 'puma-india',
        logo: '👟',
        shortDescription: 'Premium sportswear and athletic footwear.',
        description: 'Puma India offers premium sports shoes, clothing, and accessories. Get the latest Puma coupon codes and offers on sportswear, sneakers, and athletic gear.',
        websiteUrl: 'https://in.puma.com',
        metaTitle: 'Puma Coupons & Offers - Sports Deals',
        metaDescription: 'Shop Puma sportswear for less with verified coupon codes and exclusive deals on shoes and apparel.',
        status: 'PUBLISHED',
        isFeatured: false,
        isPopular: true,
        sortOrder: 10,
      },
    }),
    prisma.store.create({
      data: {
        name: 'Udemy',
        slug: 'udemy',
        logo: '🎓',
        shortDescription: 'Online courses from world-class instructors.',
        description: 'Udemy is the world\'s largest online learning platform with 200,000+ courses. Find Udemy coupons and promo codes for massive discounts on courses.',
        websiteUrl: 'https://www.udemy.com',
        metaTitle: 'Udemy Coupons & Offers - Course Deals',
        metaDescription: 'Learn for less with Udemy coupon codes. Get courses for as low as ₹449.',
        status: 'PUBLISHED',
        isFeatured: false,
        isPopular: false,
        sortOrder: 11,
      },
    }),
    prisma.store.create({
      data: {
        name: 'Boat',
        slug: 'boat',
        logo: '🎧',
        shortDescription: 'India\'s top audio brand for earphones and speakers.',
        description: 'boAt is India\'s leading audio and wearables brand offering headphones, earphones, speakers, and smartwatches. Find exclusive boAt coupons and deals.',
        websiteUrl: 'https://www.boat-lifestyle.com',
        metaTitle: 'boAt Coupons & Offers - Audio Deals',
        metaDescription: 'Shop boAt earphones and speakers for less with verified coupon codes and deals.',
        status: 'PUBLISHED',
        isFeatured: false,
        isPopular: false,
        sortOrder: 12,
      },
    }),
  ]);

  console.log(`✅ Created ${stores.length} stores`);

  // === STORE-CATEGORY MAPPINGS ===
  const storeMap = Object.fromEntries(stores.map((s) => [s.slug, s.id]));
  const catMap = Object.fromEntries(categories.map((c) => [c.slug, c.id]));

  await prisma.storeCategory.createMany({
    data: [
      { storeId: storeMap['amazon-india'], categoryId: catMap['electronics'] },
      { storeId: storeMap['amazon-india'], categoryId: catMap['fashion'] },
      { storeId: storeMap['amazon-india'], categoryId: catMap['home-living'] },
      { storeId: storeMap['flipkart'], categoryId: catMap['electronics'] },
      { storeId: storeMap['flipkart'], categoryId: catMap['fashion'] },
      { storeId: storeMap['flipkart'], categoryId: catMap['home-living'] },
      { storeId: storeMap['myntra'], categoryId: catMap['fashion'] },
      { storeId: storeMap['swiggy'], categoryId: catMap['food-dining'] },
      { storeId: storeMap['zomato'], categoryId: catMap['food-dining'] },
      { storeId: storeMap['makemytrip'], categoryId: catMap['travel'] },
      { storeId: storeMap['nykaa'], categoryId: catMap['health-beauty'] },
      { storeId: storeMap['ajio'], categoryId: catMap['fashion'] },
      { storeId: storeMap['croma'], categoryId: catMap['electronics'] },
      { storeId: storeMap['puma-india'], categoryId: catMap['fashion'] },
      { storeId: storeMap['puma-india'], categoryId: catMap['sports-fitness'] },
      { storeId: storeMap['udemy'], categoryId: catMap['books-education'] },
      { storeId: storeMap['boat'], categoryId: catMap['electronics'] },
    ],
  });

  console.log('✅ Created store-category mappings');

  // === COUPONS ===
  const now = new Date();
  const in30Days = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
  const in7Days = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
  const in2Days = new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000);
  const in90Days = new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000);

  const coupons = await Promise.all([
    prisma.coupon.create({
      data: {
        title: 'Flat 10% Off on All Electronics',
        slug: 'amazon-10-off-electronics',
        description: 'Get flat 10% discount on all electronic products including smartphones, laptops, tablets, and accessories. Maximum discount ₹1,500. Valid on minimum purchase of ₹3,000.',
        code: 'ELEC10',
        couponType: 'CODE',
        discountType: 'PERCENTAGE',
        discountValue: 10,
        minimumOrderValue: 3000,
        maximumDiscount: 1500,
        couponUrl: 'https://www.amazon.in/electronics',
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: true,
        sortOrder: 1,
        clickCount: 342,
        storeId: storeMap['amazon-india'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Amazon New User ₹200 Off',
        slug: 'amazon-new-user-200-off',
        description: 'Welcome to Amazon! Get ₹200 off on your first order. No minimum purchase required. Valid for new users only.',
        code: 'WELCOME200',
        couponType: 'CODE',
        discountType: 'FIXED_AMOUNT',
        discountValue: 200,
        couponUrl: 'https://www.amazon.in',
        startsAt: now,
        expiresAt: in90Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: true,
        sortOrder: 2,
        clickCount: 1256,
        storeId: storeMap['amazon-india'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Free Shipping on Orders Above ₹499',
        slug: 'amazon-free-shipping-499',
        description: 'Enjoy free shipping on all Amazon orders above ₹499. No coupon code needed, applied automatically at checkout.',
        couponType: 'NO_CODE',
        discountType: 'FREE_SHIPPING',
        minimumOrderValue: 499,
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: false,
        sortOrder: 3,
        clickCount: 89,
        storeId: storeMap['amazon-india'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Flipkart Big Savings Days - Extra 15% Off',
        slug: 'flipkart-big-savings-15-off',
        description: 'Get extra 15% off during Flipkart Big Savings Days sale. Valid on fashion, electronics, and home products. Max discount ₹2,000.',
        code: 'BIGSAVE15',
        couponType: 'CODE',
        discountType: 'PERCENTAGE',
        discountValue: 15,
        minimumOrderValue: 1999,
        maximumDiscount: 2000,
        couponUrl: 'https://www.flipkart.com/big-savings-days',
        startsAt: now,
        expiresAt: in7Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: true,
        sortOrder: 1,
        clickCount: 567,
        storeId: storeMap['flipkart'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Flipkart Axis Bank Card - 5% Unlimited Cashback',
        slug: 'flipkart-axis-bank-cashback',
        description: 'Get 5% unlimited cashback on all Flipkart purchases when you pay with Flipkart Axis Bank Credit Card. No minimum order value.',
        couponType: 'NO_CODE',
        discountType: 'CASHBACK',
        discountValue: 5,
        startsAt: now,
        expiresAt: in90Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: false,
        sortOrder: 2,
        clickCount: 234,
        storeId: storeMap['flipkart'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Myntra End of Reason Sale - Extra 20% Off',
        slug: 'myntra-eors-20-off',
        description: 'During Myntra\'s End of Reason Sale, get an extra 20% off on already discounted fashion products. Use code at checkout. Min order ₹1,499.',
        code: 'EORS20',
        couponType: 'CODE',
        discountType: 'PERCENTAGE',
        discountValue: 20,
        minimumOrderValue: 1499,
        maximumDiscount: 800,
        couponUrl: 'https://www.myntra.com/eors',
        startsAt: now,
        expiresAt: in7Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: true,
        sortOrder: 1,
        clickCount: 890,
        storeId: storeMap['myntra'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Myntra First Purchase - Flat ₹300 Off',
        slug: 'myntra-first-purchase-300',
        description: 'New to Myntra? Get flat ₹300 off on your first purchase. Minimum order ₹999. Valid for new registered users only.',
        code: 'MYNTRANEW',
        couponType: 'CODE',
        discountType: 'FIXED_AMOUNT',
        discountValue: 300,
        minimumOrderValue: 999,
        couponUrl: 'https://www.myntra.com',
        startsAt: now,
        expiresAt: in90Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: false,
        sortOrder: 2,
        clickCount: 445,
        storeId: storeMap['myntra'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Swiggy 50% Off - Up to ₹100',
        slug: 'swiggy-50-off-new-users',
        description: 'Get 50% off on your first 5 Swiggy orders. Maximum discount ₹100 per order. Valid for new users only.',
        code: 'SWIGGYIT',
        couponType: 'CODE',
        discountType: 'PERCENTAGE',
        discountValue: 50,
        maximumDiscount: 100,
        couponUrl: 'https://www.swiggy.com',
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: true,
        sortOrder: 1,
        clickCount: 2341,
        storeId: storeMap['swiggy'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Swiggy Free Delivery on All Orders',
        slug: 'swiggy-free-delivery',
        description: 'Enjoy free delivery on all Swiggy orders with Swiggy One membership. No minimum order value required.',
        couponType: 'NO_CODE',
        discountType: 'FREE_SHIPPING',
        startsAt: now,
        expiresAt: in90Days,
        status: 'PUBLISHED',
        isVerified: false,
        isFeatured: false,
        sortOrder: 2,
        clickCount: 156,
        storeId: storeMap['swiggy'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Zomato ₹125 Off on First Order',
        slug: 'zomato-125-off-first-order',
        description: 'Welcome to Zomato! Get ₹125 off on your first food delivery order. No minimum order value. Valid for new users only.',
        code: 'ZOMATO125',
        couponType: 'CODE',
        discountType: 'FIXED_AMOUNT',
        discountValue: 125,
        couponUrl: 'https://www.zomato.com',
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: true,
        sortOrder: 1,
        clickCount: 1890,
        storeId: storeMap['zomato'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'MakeMyTrip Flat ₹1,200 Off on Domestic Flights',
        slug: 'makemytrip-1200-off-flights',
        description: 'Get flat ₹1,200 instant discount on domestic flight bookings. Min booking value ₹5,000. Valid on select routes.',
        code: 'MMTFLY',
        couponType: 'CODE',
        discountType: 'FIXED_AMOUNT',
        discountValue: 1200,
        minimumOrderValue: 5000,
        couponUrl: 'https://www.makemytrip.com/flights',
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: true,
        sortOrder: 1,
        clickCount: 678,
        storeId: storeMap['makemytrip'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'MakeMyTrip 25% Off on Hotels',
        slug: 'makemytrip-25-off-hotels',
        description: 'Save 25% on hotel bookings at MakeMyTrip. Max discount ₹5,000. Valid on domestic and international hotels.',
        code: 'MMTHOTEL25',
        couponType: 'CODE',
        discountType: 'PERCENTAGE',
        discountValue: 25,
        minimumOrderValue: 3000,
        maximumDiscount: 5000,
        couponUrl: 'https://www.makemytrip.com/hotels',
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: false,
        sortOrder: 2,
        clickCount: 345,
        storeId: storeMap['makemytrip'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Nykaa Buy 2 Get 20% Off on Skincare',
        slug: 'nykaa-buy2-get-20-off',
        description: 'Buy any 2 skincare products and get flat 20% off. Valid on select premium and popular brands. No coupon code needed.',
        couponType: 'NO_CODE',
        discountType: 'PERCENTAGE',
        discountValue: 20,
        couponUrl: 'https://www.nykaa.com/skincare',
        startsAt: now,
        expiresAt: in7Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: true,
        sortOrder: 1,
        clickCount: 423,
        storeId: storeMap['nykaa'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'AJIO Flat 40% Off on Entire Range',
        slug: 'ajio-40-off-all',
        description: 'Get flat 40% off on AJIO\'s entire range of fashion products. Valid on clothing, footwear, and accessories. No minimum purchase.',
        code: 'AJIO40',
        couponType: 'CODE',
        discountType: 'PERCENTAGE',
        discountValue: 40,
        couponUrl: 'https://www.ajio.com',
        startsAt: now,
        expiresAt: in2Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: false,
        sortOrder: 1,
        clickCount: 567,
        storeId: storeMap['ajio'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Croma Exchange Bonus - Extra ₹3,000 Off',
        slug: 'croma-exchange-bonus-3000',
        description: 'Get extra ₹3,000 exchange bonus on smartphones and laptops at Croma. Valid on select models. Exchange your old device and save more.',
        couponType: 'NO_CODE',
        discountType: 'FIXED_AMOUNT',
        discountValue: 3000,
        couponUrl: 'https://www.croma.com/exchange',
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isVerified: false,
        isFeatured: false,
        sortOrder: 1,
        clickCount: 189,
        storeId: storeMap['croma'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Puma End of Season Sale - Flat 50% Off',
        slug: 'puma-50-off-eoss',
        description: 'Puma End of Season Sale is live! Get flat 50% off on select styles. Shop shoes, t-shirts, shorts, and sports accessories at half price.',
        couponType: 'NO_CODE',
        discountType: 'PERCENTAGE',
        discountValue: 50,
        couponUrl: 'https://in.puma.com/sale',
        startsAt: now,
        expiresAt: in7Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: true,
        sortOrder: 1,
        clickCount: 712,
        storeId: storeMap['puma-india'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'Udemy Courses Starting at ₹449',
        slug: 'udemy-courses-449',
        description: 'Learn anything with Udemy! Courses starting at just ₹449 during the sale. Choose from 200,000+ courses on development, business, design, and more.',
        couponType: 'NO_CODE',
        discountType: 'OTHER',
        couponUrl: 'https://www.udemy.com',
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: false,
        sortOrder: 1,
        clickCount: 234,
        storeId: storeMap['udemy'],
      },
    }),
    prisma.coupon.create({
      data: {
        title: 'boAt 30% Off on New Arrivals',
        slug: 'boat-30-off-new-arrivals',
        description: 'Get 30% off on boAt\'s latest earphones, speakers, and smartwatches. Use code at checkout for instant discount.',
        code: 'BOATNEW30',
        couponType: 'CODE',
        discountType: 'PERCENTAGE',
        discountValue: 30,
        maximumDiscount: 1000,
        couponUrl: 'https://www.boat-lifestyle.com/new',
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: false,
        sortOrder: 1,
        clickCount: 345,
        storeId: storeMap['boat'],
      },
    }),
    // Buy one get one
    prisma.coupon.create({
      data: {
        title: 'Myntra Buy 1 Get 1 Free on T-Shirts',
        slug: 'myntra-bogo-tshirts',
        description: 'Buy any 1 t-shirt and get another one free! Valid on select brands. Add 2 t-shirts to cart and the cheaper one is free.',
        couponType: 'NO_CODE',
        discountType: 'BOGO',
        couponUrl: 'https://www.myntra.com/tshirts',
        startsAt: now,
        expiresAt: in7Days,
        status: 'PUBLISHED',
        isVerified: true,
        verifiedAt: now,
        isFeatured: false,
        sortOrder: 3,
        clickCount: 678,
        storeId: storeMap['myntra'],
      },
    }),
  ]);

  console.log(`✅ Created ${coupons.length} coupons`);

  // === COUPON-CATEGORY MAPPINGS ===
  const couponMap = Object.fromEntries(coupons.map((c) => [c.slug, c.id]));

  await prisma.couponCategory.createMany({
    data: [
      { couponId: couponMap['amazon-10-off-electronics'], categoryId: catMap['electronics'] },
      { couponId: couponMap['amazon-new-user-200-off'], categoryId: catMap['electronics'] },
      { couponId: couponMap['amazon-new-user-200-off'], categoryId: catMap['fashion'] },
      { couponId: couponMap['flipkart-big-savings-15-off'], categoryId: catMap['electronics'] },
      { couponId: couponMap['flipkart-big-savings-15-off'], categoryId: catMap['fashion'] },
      { couponId: couponMap['myntra-eors-20-off'], categoryId: catMap['fashion'] },
      { couponId: couponMap['myntra-first-purchase-300'], categoryId: catMap['fashion'] },
      { couponId: couponMap['myntra-bogo-tshirts'], categoryId: catMap['fashion'] },
      { couponId: couponMap['swiggy-50-off-new-users'], categoryId: catMap['food-dining'] },
      { couponId: couponMap['swiggy-free-delivery'], categoryId: catMap['food-dining'] },
      { couponId: couponMap['zomato-125-off-first-order'], categoryId: catMap['food-dining'] },
      { couponId: couponMap['makemytrip-1200-off-flights'], categoryId: catMap['travel'] },
      { couponId: couponMap['makemytrip-25-off-hotels'], categoryId: catMap['travel'] },
      { couponId: couponMap['nykaa-buy2-get-20-off'], categoryId: catMap['health-beauty'] },
      { couponId: couponMap['ajio-40-off-all'], categoryId: catMap['fashion'] },
      { couponId: couponMap['croma-exchange-bonus-3000'], categoryId: catMap['electronics'] },
      { couponId: couponMap['puma-50-off-eoss'], categoryId: catMap['fashion'] },
      { couponId: couponMap['puma-50-off-eoss'], categoryId: catMap['sports-fitness'] },
      { couponId: couponMap['udemy-courses-449'], categoryId: catMap['books-education'] },
      { couponId: couponMap['boat-30-off-new-arrivals'], categoryId: catMap['electronics'] },
    ],
  });

  console.log('✅ Created coupon-category mappings');

  // === DEALS ===
  const deals = await Promise.all([
    prisma.deal.create({
      data: {
        title: 'iPhone 15 at Lowest Price Ever',
        slug: 'iphone-15-lowest-price',
        description: 'Apple iPhone 15 (128GB) available at the lowest price ever on Amazon. Includes bank offers and exchange bonus for even more savings.',
        productName: 'Apple iPhone 15 (128GB)',
        productImage: '📱',
        productUrl: 'https://www.amazon.in/dp/B0CHX1W1XY',
        originalPrice: 79900,
        salePrice: 57999,
        currency: 'INR',
        discountType: 'PERCENTAGE',
        discountValue: 27,
        startsAt: now,
        expiresAt: in7Days,
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 1,
        clickCount: 1456,
        storeId: storeMap['amazon-india'],
      },
    }),
    prisma.deal.create({
      data: {
        title: 'Samsung Galaxy S24 FE - Special Edition Deal',
        slug: 'samsung-s24-fe-deal',
        description: 'Samsung Galaxy S24 FE with 8GB RAM and 128GB storage at an unbeatable price. Includes Galaxy AI features and 5G support.',
        productName: 'Samsung Galaxy S24 FE (8GB/128GB)',
        productImage: '📱',
        productUrl: 'https://www.flipkart.com',
        originalPrice: 59999,
        salePrice: 39999,
        currency: 'INR',
        discountType: 'PERCENTAGE',
        discountValue: 33,
        startsAt: now,
        expiresAt: in7Days,
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 2,
        clickCount: 892,
        storeId: storeMap['flipkart'],
      },
    }),
    prisma.deal.create({
      data: {
        title: 'Nike Air Max 270 - Under ₹8,000',
        slug: 'nike-air-max-270-deal',
        description: 'Nike Air Max 270 running shoes available at Myntra for under ₹8,000. Multiple colors available. Limited stock.',
        productName: 'Nike Air Max 270',
        productImage: '👟',
        productUrl: 'https://www.myntra.com',
        originalPrice: 12995,
        salePrice: 7797,
        currency: 'INR',
        discountType: 'PERCENTAGE',
        discountValue: 40,
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 1,
        clickCount: 567,
        storeId: storeMap['myntra'],
      },
    }),
    prisma.deal.create({
      data: {
        title: 'Sony WH-1000XM5 Headphones - Best Price',
        slug: 'sony-wh1000xm5-deal',
        description: 'Sony WH-1000XM5 industry-leading noise cancelling headphones. Premium sound quality with 30-hour battery life.',
        productName: 'Sony WH-1000XM5',
        productImage: '🎧',
        productUrl: 'https://www.croma.com',
        originalPrice: 34990,
        salePrice: 24990,
        currency: 'INR',
        discountType: 'PERCENTAGE',
        discountValue: 29,
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 1,
        clickCount: 345,
        storeId: storeMap['croma'],
      },
    }),
    prisma.deal.create({
      data: {
        title: 'Goa 3N/4D Package from ₹8,499/person',
        slug: 'goa-package-8499',
        description: 'All-inclusive Goa holiday package starting at ₹8,499 per person. Includes flights, 3-star hotel, breakfast, and airport transfers.',
        productName: 'Goa 3N/4D Holiday Package',
        productImage: '🏖️',
        productUrl: 'https://www.makemytrip.com/holidays',
        originalPrice: 14999,
        salePrice: 8499,
        currency: 'INR',
        discountType: 'PERCENTAGE',
        discountValue: 43,
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 1,
        clickCount: 789,
        storeId: storeMap['makemytrip'],
      },
    }),
    prisma.deal.create({
      data: {
        title: 'Nykaa Hot Pink Sale - Makeup Kits from ₹499',
        slug: 'nykaa-hot-pink-sale',
        description: 'Nykaa Hot Pink Sale is live! Get premium makeup kits starting at just ₹499. Includes top brands like MAC, Lakme, and Maybelline.',
        productName: 'Premium Makeup Kits',
        productImage: '💄',
        productUrl: 'https://www.nykaa.com/sale',
        originalPrice: 1999,
        salePrice: 499,
        currency: 'INR',
        discountType: 'PERCENTAGE',
        discountValue: 75,
        startsAt: now,
        expiresAt: in2Days,
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 1,
        clickCount: 1234,
        storeId: storeMap['nykaa'],
      },
    }),
    prisma.deal.create({
      data: {
        title: 'boAt Airdopes 141 - Just ₹999',
        slug: 'boat-airdopes-141-999',
        description: 'boAt Airdopes 141 TWS earbuds with 42H playback, ENx Technology, and BEAST Mode for gaming. Best-selling earbuds at an unbeatable price.',
        productName: 'boAt Airdopes 141',
        productImage: '🎧',
        productUrl: 'https://www.boat-lifestyle.com',
        originalPrice: 2490,
        salePrice: 999,
        currency: 'INR',
        discountType: 'PERCENTAGE',
        discountValue: 60,
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isFeatured: false,
        sortOrder: 1,
        clickCount: 456,
        storeId: storeMap['boat'],
      },
    }),
    prisma.deal.create({
      data: {
        title: 'Puma RS-X Sneakers - Flat 55% Off',
        slug: 'puma-rsx-sneakers-55-off',
        description: 'Puma RS-X sneakers with retro-inspired design, now at 55% off. Premium cushioning and bold color options available.',
        productName: 'Puma RS-X Sneakers',
        productImage: '👟',
        productUrl: 'https://in.puma.com',
        originalPrice: 8999,
        salePrice: 4049,
        currency: 'INR',
        discountType: 'PERCENTAGE',
        discountValue: 55,
        startsAt: now,
        expiresAt: in7Days,
        status: 'PUBLISHED',
        isFeatured: false,
        sortOrder: 1,
        clickCount: 234,
        storeId: storeMap['puma-india'],
      },
    }),
    prisma.deal.create({
      data: {
        title: 'MacBook Air M2 - ₹20,000 Off',
        slug: 'macbook-air-m2-deal',
        description: 'Apple MacBook Air M2 (256GB) at ₹20,000 off. Perfect for students and professionals. Includes AppleCare+ option.',
        productName: 'Apple MacBook Air M2 (256GB)',
        productImage: '💻',
        productUrl: 'https://www.flipkart.com',
        originalPrice: 99900,
        salePrice: 79900,
        currency: 'INR',
        discountType: 'FIXED_AMOUNT',
        discountValue: 20000,
        startsAt: now,
        expiresAt: in30Days,
        status: 'PUBLISHED',
        isFeatured: true,
        sortOrder: 3,
        clickCount: 678,
        storeId: storeMap['flipkart'],
      },
    }),
    prisma.deal.create({
      data: {
        title: 'AJIO Sneaker Fest - Starting ₹999',
        slug: 'ajio-sneaker-fest-999',
        description: 'AJIO Sneaker Fest is live! Premium sneakers from Nike, Adidas, Puma, and more starting at just ₹999. Limited period offer.',
        productName: 'Premium Sneakers Collection',
        productImage: '👟',
        productUrl: 'https://www.ajio.com/sneakers',
        originalPrice: 4999,
        salePrice: 999,
        currency: 'INR',
        discountType: 'PERCENTAGE',
        discountValue: 80,
        startsAt: now,
        expiresAt: in7Days,
        status: 'PUBLISHED',
        isFeatured: false,
        sortOrder: 1,
        clickCount: 890,
        storeId: storeMap['ajio'],
      },
    }),
  ]);

  console.log(`✅ Created ${deals.length} deals`);

  // === DEAL-CATEGORY MAPPINGS ===
  const dealMap = Object.fromEntries(deals.map((d) => [d.slug, d.id]));

  await prisma.dealCategory.createMany({
    data: [
      { dealId: dealMap['iphone-15-lowest-price'], categoryId: catMap['electronics'] },
      { dealId: dealMap['samsung-s24-fe-deal'], categoryId: catMap['electronics'] },
      { dealId: dealMap['nike-air-max-270-deal'], categoryId: catMap['fashion'] },
      { dealId: dealMap['nike-air-max-270-deal'], categoryId: catMap['sports-fitness'] },
      { dealId: dealMap['sony-wh1000xm5-deal'], categoryId: catMap['electronics'] },
      { dealId: dealMap['goa-package-8499'], categoryId: catMap['travel'] },
      { dealId: dealMap['nykaa-hot-pink-sale'], categoryId: catMap['health-beauty'] },
      { dealId: dealMap['boat-airdopes-141-999'], categoryId: catMap['electronics'] },
      { dealId: dealMap['puma-rsx-sneakers-55-off'], categoryId: catMap['fashion'] },
      { dealId: dealMap['puma-rsx-sneakers-55-off'], categoryId: catMap['sports-fitness'] },
      { dealId: dealMap['macbook-air-m2-deal'], categoryId: catMap['electronics'] },
      { dealId: dealMap['ajio-sneaker-fest-999'], categoryId: catMap['fashion'] },
    ],
  });

  console.log('✅ Created deal-category mappings');

  console.log('\n🎉 Seeding complete! Database is ready.');
  console.log(`   📦 ${stores.length} stores`);
  console.log(`   🏷️  ${categories.length} categories`);
  console.log(`   🎟️  ${coupons.length} coupons`);
  console.log(`   🔥 ${deals.length} deals`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('❌ Seed error:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
